core/blog/api/v1/urls.py
from django.urls import path,include
from . import views
from rest_framework.routers import DefaultRouter
app_name = 'api-v1'

router = DefaultRouter()
router.register('post',views.PostViewSet,basename='post')
router.register('category',views.CategoryViewSet,basename='category')
urlpatterns = router.urls

# urlpatterns = [
#     # path('post/',views.postList,name='post-list'),
#     # path('post/<int:id>/',views.postDetail,name='post-detail'),
#     # path('post/',views.PostList.as_view(),name='post-list'),   
#     # path('post/<int:pk>/',views.PostDetail.as_view(),name='post-detail'),
#     path('post/',views.PostViewSet.as_view({'get':'list'}),name='post-list'),
#     path('post/<int:pk>/',views.PostViewSet.as_view({'get':'retrieve','put':'update'}),name='post-detail'),
# ]

core/blog/urls.py
from django.urls import path,include
from . import views
from django.views.generic import TemplateView,RedirectView
app_name = 'blog'
urlpatterns = [
    # path("cbv-index",views.IndexView.as_view(),name='cbv-index'),
    # path('go-to-maktabkhooneh/', views.RedirectToMaktab.as_view(), name='redirect-to-maktabkhooneh'),
    path('post/',views.PostListView.as_view(),name='post-list'),
    path('post/<int:pk>',views.PostDetailView.as_view(),name='post-detail'),
    path('post/create',views.PostCreateView.as_view(),name='post-create'),
    path('post/<int:pk>/edit',views.PostEditView.as_view(),name='post-edit'),
    path('post/<int:pk>/delete',views.PostDeleteView.as_view(),name='post-delete'),
    path('api/v1/',include('blog.api.v1.urls'))


]

core/core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.documentation import include_docs_urls
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

# API Document
schema_view = get_schema_view(
   openapi.Info(
      title="Blog Api",
      default_version='v1',
      description="This is a test api",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=[permissions.AllowAny],
)




urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('accounts/',include('accounts.urls')),
    path('api-docs/',include_docs_urls(title='api sample')),
    path('swagger/output.json', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/blog/models.py
from django.db import models
# from accounts.models import Profile
from django.contrib.auth import get_user_model
from django.urls import reverse
# Create your models here.

# User =  get_user_model()

class Post(models.Model):
    author = models.ForeignKey('accounts.Profile',on_delete=models.CASCADE)
    image = models.ImageField(blank=True,null=True)
    title = models.CharField(max_length=250)
    content = models.TextField()
    status = models.BooleanField()
    category  = models.ForeignKey("Category",on_delete=models.SET_NULL,null=True)
    

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField()

    def __str__(self):
        return self.title
    
    def get_snippet(self):
        return self.content[0:5]
    
    def get_absolute_api_url(self):
        return reverse('blog:api-v1:post-detail',kwargs={"pk":self.pk})
    
class Category(models.Model):
    name = models.CharField(max_length=250)
    

    def __str__(self):
        return self.name

core/blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title','content','status','category','published_date']

core/blog/api/v1/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response
from ...models import Post,Category
from rest_framework import status
from rest_framework.permissions import IsAuthenticated,IsAuthenticatedOrReadOnly
from .serializer import *
from rest_framework.views import APIView
from rest_framework.generics import ListCreateAPIView,RetrieveUpdateDestroyAPIView,UpdateAPIView
from rest_framework.viewsets import ViewSet,ModelViewSet
from django.shortcuts import get_object_or_404
from .permission import IsOwnerOrReadOnly
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import SearchFilter,OrderingFilter
from .paginations import DefaultPagination
from .filters import ProductFilter
'''
@api_view(['GET', 'POST'])
def postList(request):
    if request.method == 'GET':        
        posts = Post.objects.filter(status=1)
        # many = true,means that more than one object will be displayed on the web page
        serializer = PostSerializer(posts,many=True)
        return Response(serializer.data)
    elif request.method == 'POST':
        serializer = PostSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)'''


'''
@api_view(['GET', 'PUT','DELETE'])
def postDetail(request, id):
    if request.method == 'GET':
        try:
            post = Post.objects.get(pk=id)
            serializer = PostSerializer(post)
            return Response(serializer.data)
        except Post.DoesNotExist:
            return Response({'Detail': f'post {id} does not exist'}, status=status.HTTP_404_NOT_FOUND)
    elif request.method == 'PUT':
        post = Post.objects.get(pk=id)
        # The code below is to convert the post and the changes made in it to Json
        serializer = PostSerializer(post,data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(request.data)
    elif request.method == "DELETE":
        post = Post.objects.get(pk=id)
        post.delete()
        return Response({'detail':'item removed successfully'},status=status.HTTP_204_NO_CONTENT)
'''


"""class PostList(APIView):
    permission_classes = [IsAuthenticatedOrReadOnly]
    serializer_class = PostSerializer
    def get(self,request):
        posts = Post.objects.filter(status=1)
        # many = true,means that more than one object will be displayed on the web page
        serializer = PostSerializer(posts,many=True)
        return Response(serializer.data)
    def post(self,request):
        serializer = PostSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)
"""
    
# class PostDetail(APIView):
#     permission_classes = [IsAuthenticated]
#     serializer_class = PostSerializer

#     def get(self,request,id):
#         try:
#             post = Post.objects.get(pk=id)
#             serializer = self.serializer_class(post)
#             return Response(serializer.data)
#         except Post.DoesNotExist:
#             return Response({'Detail': f'post {id} does not exist'}, status=status.HTTP_404_NOT_FOUND)
#     def put(self,request,id):
#         post = Post.objects.get(pk=id)
#         # The code below is to convert the post and the changes made in it to Json
#         serializer = self.serializer_class(post,data=request.data)
#         serializer.is_valid(raise_exception=True)
#         serializer.save()
#         return Response(request.data)
#     def delete(self,request,id):
#         post = Post.objects.get(pk=id)
#         post.delete()
#         return Response({'detail':'item removed successfully'},status=status.HTTP_204_NO_CONTENT)

# class PostViewSet(ViewSet):
#     queryset = Post.objects.all()
#     permission_classes = [IsAuthenticatedOrReadOnly]
#     serializer_class = PostSerializer

#     def list(self, request):
#         serializers = self.serializer_class(self.queryset,many=True)
#         return Response(serializers.data)
    
#     def retrieve(self, request,pk=None):
#         post_object = get_object_or_404(self.queryset,pk=pk)
#         serializers = self.serializer_class(post_object)
#         return Response(serializers.data)
#     def update(self,request,*args,**kwargs):
#         return self.update(request,*args,**kwargs)


# class PostList(ListCreateAPIView):
#     queryset = Post.objects.all()
#     permission_classes = [IsAuthenticatedOrReadOnly]
#     serializer_class = PostSerializer

    
# class PostDetail(RetrieveUpdateDestroyAPIView):
#     queryset = Post.objects.filter(status=1)
#     permission_classes = [IsAuthenticated]
#     serializer_class = PostSerializer


class PostViewSet(ModelViewSet):
    queryset = Post.objects.all()
    permission_classes = [IsAuthenticated,IsOwnerOrReadOnly]
    serializer_class = PostSerializer
    filter_backends = [DjangoFilterBackend,SearchFilter,OrderingFilter]
    # filterset_fields = ['category', 'author','status']
    search_fields = ['title', 'content']
    ordering_fields = ['published_date']
    pagination_class = DefaultPagination
    filterset_class = ProductFilter


class CategoryViewSet(ModelViewSet):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer
    permission_classes = [IsAuthenticatedOrReadOnly]

core/blog/views.py
from typing import Any, List, Sequence
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render
from .models import Post
from accounts.models import Profile
from django.views.generic import TemplateView,RedirectView
from django.views.generic import ListView,DetailView,FormView,CreateView,UpdateView,DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from .forms import PostForm
# Create your views here.

# def indexView(request):
#     posts = Post.objects.all()
#     context = {'posts': posts}
#     return render(request,'index.html',context)

class IndexView(TemplateView):
    template_name = 'index.html'
    """super = TemplateView"""
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = 'https://maktabkhooneh.org/'
        return context

class RedirectToMaktab(RedirectView):
    url = 'https://maktabkhooneh.org/'
    
class PostListView(LoginRequiredMixin,ListView):
    # model = Post
    paginate_by = 2
    queryset = Post.objects.all()
    context_object_name = 'posts'
    ordering = '-id'

    # def get_queryset(self):
    #     posts = Post.objects.filter(status=1).order_by('-id').all()
    #     return posts
class PostDetailView(LoginRequiredMixin,DetailView):
    model = Post


class PostCreateView(FormView):
    template_name = 'contact.html'
    form_class = PostForm
    success_url = '/blog/post/'

    def form_valid(self,form):
        form.save()
        return super().form_valid(form)


class PostCreateView(LoginRequiredMixin,CreateView):
    model = Post
    # fields = ['author','title','content','status','category','published_date']
    template_name = 'blog/form.html'
    form_class = PostForm    
    success_url = '/blog/post/'

class PostEditView(LoginRequiredMixin,UpdateView):
    model = Post
    form_class = PostForm
    success_url = '/blog/post/'


class PostDeleteView(LoginRequiredMixin,DeleteView):
    model = Post
    success_url = '/blog/post/'
    

core/templates/blog/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Post Create</title>
</head>
<body>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
</body>
</html>

core/templates/blog/post_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        {{ form }}
        <input type="submit" value="Confirm">
    </form>
</body>
</html>

core/templates/blog/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{object.title}}</h1>
    <hr>
    <small>{{object.author.first_name}} - {{object.published_date}}</small>
    <p>{{object.content}}</p>
</body>
</html>

core/templates/blog/post_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
</body>
</html>

core/templates/blog/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Blog Post</h1>
    <ol>
        {% for post in posts %}
    <div>
        <a href="{% url 'blog:post-detail' pk=post.id %}"><h2>{{post.id}}-{{post.title}}</h2></a>
        <p>{{post.content}}</p>
        <a href="{% url 'blog:post-edit' pk=post.id %}">
            <h5>Edit</h5>
        </a>
        <a href="{% url 'blog:post-delete' pk=post.id %}">
            <h5>Delete</h5>
        </a>
        <small>{{post.author.first_name}} {{post.author.last_name}} - {{post.published_date}}</small>
    </div>
        {% endfor %}
    </ol>
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</body>
</html>